package CDProject.vfmarket.domain.entity;

public enum WriteStatus {
    REVIEW_AVAILABLE, REVIEW_NOT_AVAILABLE, INQUIRY_AVAILABLE, INQUIRY_NOT_AVAILABLE,
    COMMENT_AVAILABLE, COMMENT_NOT_AVAILABLE, REPLIES_AVAILABLE, REPLIES_NOT_AVAILABLE
}
